repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # bump to latest version when needed
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2 # bump to latest version when needed
    hooks:
      - id: black
        files: server/.+\.py$ # regex that matches files to be checked
        types: ["file"]
        args: [--line-length=160]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2 # bump to latest version when needed
    hooks:
      - id: isort
        files: server/.+\.py$ # regex that matches files to be checked
        types: ["file"]
        args: ["--profile", "black"]
