version: "3.3"
services:
  db:
    image: "mongo:4.4"
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    volumes:
      - "ots-db:/data/db"

  backend:
    build:
      context: "."
      dockerfile: "Dockerfile.backend"
    restart: "unless-stopped"
    ports:
      - "80:80"
    environment:
      MONGO_COL: secret
      MONGO_DB: ots
      MONGO_HOST: db
      MONGO_USERNAME: ${MONGO_USR}
      MONGO_PORT: 27017
      MONGO_PASSWORD: ${MONGO_PWD}
    depends_on:
      - "db"

  web:
    build:
      context: "."
      dockerfile: "Dockerfile.web"
    restart: "unless-stopped"
    ports:
      - "8080:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - "backend"

volumes:
  ots-db:
