version: "3.3"
services:
  web:
    build:
      context: "."
      dockerfile: "Dockerfile.proxy"
    restart: "unless-stopped"
    ports:
      - "8080:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - "backend"

